### ISSUE TITLE
No joy installing

### ISSUE THREAD

**Issue by DaveC426913** [jxpx777/js-csv-parser#5]
I am trying to use your CSV parser but having trouble getting to 'hello world'. I either have it installed wrong, or am calling it wrong.

I'm reading a file from disk using FileReader. My test CSV looks like this:
"foo!!","bar"
"foo!!","bar"

This is my code:
        var options = {
            fieldSeparator : ",",
            strict : true,
            ignoreEmpty: true
        };

```
    var csv = new CSVParser(text,options);
    console.log(text);
    console.log(csv.parse());
```

My output (which is error-free) is

"foo!!","bar"
"foo!!","bar"
undefined

**Comment by jxpx777** [comment]
After `csv.parse()`, the parser `csv` will have a `rows` property that's an array of arrays. So, something like this:

```
var csv = new CSVParser(text,options);
csv.parse();
csv.rows.forEach(function(row) {
    console.log(JSON.stringify(row));
});
```

The `row` parameter will be an array of the fields for the given row. I hope that helps!

**Comment by DaveC426913** [comment]
Alas, that code results in no output at all.

Is it possible it is not correctly plugged-in? (though I would think that would results in errors and undefined's). All I've got is this in the index.html:
[ script src="public/lib/csv-parser/csv.min.js" ][ /script ]
then I refer to it directly within my controller - no dependency-injection.

**Comment by jxpx777** [comment]
Here's an example: http://jsfiddle.net/jxpx777/wu5anr56/1/

**Comment by DaveC426913** [comment]
Example does not Run:
 Refused to execute script from 'https://raw.githubusercontent.com/jxpx777/js-csv-parser/master/csv.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

(Surely, this is not a browser setting on my end; I run jsfiddles all the time...)

**Comment by jxpx777** [comment]
Ran fine here, but I updated the example to include the csv.min.js content directly instead of referencing from Github.

**Comment by DaveC426913** [comment]
New URL? Or same? Doesn't seem to be any different.

**Comment by jxpx777** [comment]
Whoops… Sorry. It's http://jsfiddle.net/jxpx777/wu5anr56/2/ because there was a new version

**Comment by DaveC426913** [comment]
That works. Thank you. That will allow me to root out what's failing in my app.

**Comment by DaveC426913** [comment]
Sorry, I just don't get it. It's coming in some format that I don't know what to do with.
I was hoping to validate that the string is valid CSV. (consistent columns, proper quotes, escape characters, etc.) I guess this was the wrong tool to do this with.

(Problem is, it seems there is just no such thing as a JavaScript CSV validator algorithm out there.
I've got a code snippet that includes a regex, but it fails on too many valid strings.)

Anyway, thanks for your help but it's back to the drawing board for me...
